---
  - name: remove six
    pip:
      name: six
      state: absent
  - name: remove docker-py
    pip:
      name: docker-py
      state: absent
  - name: install six
    pip:
      name: six
      state: present
  - name: install docker-py
    pip:
      name: docker-py
      state: present
